## Flight data

<a href="#PCA" style="text-decoration: none;">
    <button style="padding:10px; font-size:15px;">PCA</button>
</a>

<a href="#PC" style="text-decoration: none;">
    <button style="padding:10px; font-size:15px;">PCA Components</button>
</a>

<a href="#Clusters" style="text-decoration: none;">
    <button style="padding:10px; font-size:15px;">Clusters</button>
</a>

<a href="#Cluster-Visual" style="text-decoration: none;">
    <button style="padding:10px; font-size:15px;">Cluster Visual</button>
</a>

<a href="#Time-Series" style="text-decoration: none;">
    <button style="padding:10px; font-size:15px;">Time Series</button>
</a>

## Data Prep

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
L = [' PHX',' LAX',' SAN',' SFO',' DEN',' FLL',' MIA',' MCO',' TPA',' ATL',
     ' MDW',' ORD',' BWI',' BOS',' DTW',' MSP',' LAS',' EWR',' JFK',' LGA',
     ' CLT',' PHL',' BNA',' AUS',' DFW',' IAH',' SLC',' DCA',' IAD',' SEA',' MCI',' IND',' HNL',' ANC']
flight = pd.read_csv('../Detect Data/flight.csv').drop('Unnamed: 0',axis=1)
#scheduled commercial flights with dep, arr, and air delays
#airportLocation.to_csv('airportLocation.csv')

In [3]:
# a = ['PABE',' GPI','PAGA',' DGG',' SGJ',' HEF',' PFN']
# b = [' BET',' FCA',' GAL',' RDB',' UST',' MNZ',' ECP']
# flight = flight.replace(a,b)

In [3]:
wrong = ['FCA','AZA','FWH','USA','CBD',
         'CLD','QQT','XXW','GAL','SCE',
         'BKC','RDB','BKG','SPN','HAR',
         'HHH','UST']
correct = ['GPI','IWA','NFW','JQF','PACD',
          'CRQ','FFC','LCQ','PAGA','UNV',
           'PABL','DGG','BBG','GSN','CXY',
           'HXD','SGJ']
airport = pd.read_csv('../../GDP/AirportLoc/Airport_Loc.csv')
airport = airport[airport['AIRPORT_COUNTRY_CODE_ISO']=='US']
airport = airport[airport['AIRPORT_THRU_DATE'].isna()]
airport['AIRPORT'] = airport['AIRPORT'].replace(wrong,correct)
airport = airport[['AIRPORT_STATE_CODE','LATITUDE','LONGITUDE','AIRPORT']].head(-1)
airport = airport[~airport['AIRPORT_STATE_CODE'].isin(['PR','TT','VI'])]

In [4]:
airport['LOCID'] = ' '+airport['AIRPORT']

In [6]:
# flight = flight[flight['OAG']=='Y']

In [5]:
Airports = list(set(flight['DEP_LOCID'].unique())|set(flight['ARR_LOCID'].unique()))
len(Airports)#521
#Number of all U.S. airports exsits in ASPM excluding PR, TT, and VI

495

In [6]:
Airports = [x for x in Airports if x in list(airport[airport['LOCID'].isin(Airports)]['LOCID'])]#490

In [7]:
len(Airports)

490

In [8]:
Airports_temp = Airports.copy()
Airports_temp.append('PAGA')
Airports_temp.append('PAKT')
Airports_temp.append('PAVD')
Airports_temp.append('PAIL')
Airports_temp.append('PACD')
Airports_temp.append('PASN')

In [9]:
Airports_temp

[' LEB',
 ' IWA',
 ' PAH',
 ' SUN',
 ' ATY',
 ' MYR',
 ' PDT',
 ' DLG',
 ' VIS',
 ' ABY',
 ' PNS',
 ' AIA',
 ' SDP',
 ' BMI',
 ' BUF',
 ' MUO',
 ' PBG',
 ' ORH',
 ' DCA',
 ' CLT',
 ' HRO',
 ' GTR',
 ' CNM',
 ' STL',
 ' MQY',
 ' GRK',
 ' MHT',
 ' ORF',
 ' PIT',
 ' HVN',
 ' LNY',
 ' BFL',
 ' BET',
 ' ICT',
 ' TUS',
 ' BGM',
 ' BFD',
 ' FOD',
 ' GRI',
 ' CGI',
 ' IYK',
 ' EDW',
 ' BFM',
 ' MSN',
 ' BQK',
 ' BRL',
 ' CRP',
 ' ART',
 ' PKB',
 ' FOE',
 ' PHF',
 ' MSL',
 ' PRC',
 ' LIH',
 ' HSV',
 ' BPT',
 ' MCW',
 ' DLH',
 ' RAP',
 ' MSY',
 ' ELP',
 ' FKL',
 ' FSM',
 ' LWS',
 ' LAS',
 ' AKN',
 ' IND',
 ' JST',
 ' SGU',
 ' CVN',
 ' MSP',
 ' UNK',
 ' MEI',
 ' TUP',
 ' JNU',
 ' VEL',
 ' IAD',
 ' ALM',
 ' CDR',
 ' TUL',
 ' MHR',
 ' DUT',
 ' SIT',
 ' XNA',
 ' CID',
 ' MSS',
 ' UIN',
 ' FLO',
 ' TPA',
 ' CIC',
 ' WYS',
 ' ALS',
 ' GPM',
 ' MDW',
 ' BLI',
 ' TBN',
 ' ENA',
 ' DIK',
 ' HXD',
 ' TOL',
 ' CLE',
 ' BBG',
 ' AGS',
 ' IAH',
 ' EWB',
 ' ROC',
 ' FWA',
 ' LIT',
 ' LUK',
 ' ELD',
 ' MIA',
 ' YIP',
 ' CHS',
 ' GYY',
 ' DFW',
 ' ALW',
 ' SBA',
 ' COU',
 ' RDD',
 ' PIA',
 ' VPS',
 ' PIR',
 ' SAV',
 ' HOT',
 ' PBI',
 ' EVV',
 ' SWO',
 ' RNO',
 ' PIE',
 ' LAN',
 ' BHM',
 ' RIC',
 ' MCK',
 ' OKC',
 ' CRW',
 ' SYR',
 ' GTF',
 ' RFD',
 ' APF',
 ' MMU',
 ' BTL',
 ' MKG',
 ' MLI',
 ' LRD',
 ' ACK',
 ' DRT',
 ' RST',
 ' INL',
 ' GPT',
 ' ROA',
 ' IAG',
 ' GBD',
 ' HPN',
 ' CMH',
 ' BHB',
 ' HNL',
 ' MWA',
 ' ASE',
 ' BKW',
 ' WRG',
 ' PUW',
 ' IMT',
 ' OGD',
 ' AUG',
 ' RDM',
 ' SFB',
 ' BOI',
 ' HRL',
 ' DVL',
 ' FNT',
 ' TYS',
 ' ILG',
 ' TEX',
 ' MKC',
 ' SRQ',
 ' MLU',
 ' TYR',
 ' PGA',
 ' FLG',
 ' YNG',
 ' MFR',
 ' CWA',
 ' SBY',
 ' PGV',
 ' STC',
 ' JQF',
 ' BTM',
 ' ADK',
 ' RME',
 ' PVU',
 ' CEC',
 ' RSW',
 ' MKK',
 ' ABR',
 ' CSG',
 ' TVC',
 ' IPL',
 ' SPI',
 ' ATW',
 ' LBL',
 ' GGG',
 ' TWF',
 ' TTN',
 ' SBN',
 ' SHR',
 ' ATL',
 ' DAB',
 ' DRO',
 ' SEA',
 ' STS',
 ' GCC',
 ' VCV',
 ' HDN',
 ' RUT',
 ' CVG',
 ' JFK',
 ' BRW',
 ' OGG',
 ' PHX',
 ' MCI',
 ' LMT',
 ' PDX',
 ' HTS',
 ' RKS',
 ' BLV',
 ' ITO',
 ' PHL',
 ' EYW',
 ' SUX',
 ' PSP',
 ' LNK',
 ' LVK',
 ' JHM',
 ' ACV',
 ' RKD',
 ' CLL',
 ' FTW',
 ' DAL',
 ' GSO',
 ' CNY',
 ' AUO',
 ' SHD',
 ' PSG',
 ' LAX',
 ' FNL',
 ' ALB',
 ' KOA',
 ' MLB',
 ' IDA',
 ' OAK',
 ' MGW',
 ' CKB',
 ' MTJ',
 ' LSE',
 ' ROW',
 ' ONP',
 ' COS',
 ' FAY',
 ' EGE',
 ' PSM',
 ' FAT',
 ' PVD',
 ' YUM',
 ' DHN',
 ' MCO',
 ' ONT',
 ' BRO',
 ' ISP',
 ' TXK',
 ' HHR',
 ' ACY',
 ' GCK',
 ' BNA',
 ' BIL',
 ' PTK',
 ' MBS',
 ' PLN',
 ' LYH',
 ' SCK',
 ' MHK',
 ' ANI',
 ' GUS',
 ' CIU',
 ' TLH',
 ' LBF',
 ' ABE',
 ' SHV',
 ' BOS',
 ' RDU',
 ' MQT',
 ' MDT',
 ' SDF',
 ' CPR',
 ' OXR',
 ' CMX',
 ' SJC',
 ' ISN',
 ' ESC',
 ' JLN',
 ' BRD',
 ' DTW',
 ' CEZ',
 ' BTR',
 ' SOW',
 ' EWR',
 ' GJT',
 ' FFC',
 ' LGB',
 ' AEX',
 ' IPT',
 ' LUP',
 ' LBE',
 ' FAI',
 ' JAN',
 ' OAJ',
 ' LEX',
 ' AVP',
 ' GUC',
 ' HOM',
 ' PQI',
 ' OTH',
 ' BID',
 ' OMA',
 ' GLH',
 ' ADQ',
 ' HLN',
 ' DSM',
 ' SAN',
 ' ILM',
 ' GNV',
 ' ACT',
 ' CYS',
 ' PUB',
 ' UNV',
 ' LFT',
 ' GFK',
 ' ABQ',
 ' LGA',
 ' ABI',
 ' MCE',
 ' SWF',
 ' EAU',
 ' ITH',
 ' MMH',
 ' APN',
 ' EKO',
 ' TRI',
 ' BFI',
 ' PGD',
 ' SLC',
 ' OWB',
 ' PTH',
 ' TEB',
 ' LCH',
 ' BDL',
 ' FLL',
 ' SNA',
 ' ELM',
 ' RIW',
 ' MBL',
 ' GRB',
 ' BGR',
 ' VRB',
 ' PAM',
 ' ANC',
 ' JBR',
 ' CMI',
 ' BUR',
 ' GEG',
 ' HYA',
 ' DDC',
 ' DNV',
 ' FSD',
 ' HYS',
 ' OGS',
 ' NEW',
 ' GRR',
 ' COD',
 ' NFW',
 ' CXY',
 ' MAF',
 ' CDV',
 ' ADW',
 ' CHA',
 ' JAC',
 ' LCK',
 ' BED',
 ' CAK',
 ' MWH',
 ' IFP',
 ' HGR',
 ' CHO',
 ' SLE',
 ' SMX',
 ' ECP',
 ' LAR',
 ' BWG',
 ' VCT',
 ' RIV',
 ' SMF',
 ' MVY',
 ' SVC',
 ' CRQ',
 ' DEC',
 ' VNY',
 ' AZO',
 ' BWI',
 ' JHW',
 ' GSP',
 ' BMG',
 ' BZN',
 ' HON',
 ' DUJ',
 ' SGF',
 ' SBP',
 ' TVF',
 ' YAK',
 ' PDK',
 ' MOT',
 ' MCN',
 ' PAE',
 ' OME',
 ' SFO',
 ' LNS',
 ' YKM',
 ' LWB',
 ' MFE',
 ' KSM',
 ' IRK',
 ' BJI',
 ' KTN',
 ' BIS',
 ' PVC',
 ' DEN',
 ' PIH',
 ' DAY',
 ' SLN',
 ' SPS',
 ' JMS',
 ' SCC',
 ' ALO',
 ' VDZ',
 ' EAR',
 ' MGM',
 ' BFF',
 ' AUS',
 ' HOU',
 ' MKL',
 ' LCQ',
 ' EAT',
 ' AOO',
 ' AMA',
 ' OTZ',
 ' AVL',
 ' DBQ',
 ' ORD',
 ' OLV',
 ' MEM',
 ' SLK',
 ' IWD',
 ' HOB',
 ' HIB',
 ' RHI',
 ' SJT',
 ' VLD',
 ' EUG',
 ' UTM',
 ' SAT',
 ' SAF',
 ' LAF',
 ' CAE',
 ' PWM',
 ' ERI',
 ' MKE',
 ' AHN',
 ' CDC',
 ' BTV',
 ' MOB',
 ' PSC',
 ' EWN',
 ' FAR',
 ' BIH',
 ' LAW',
 ' PIB',
 ' LBB',
 ' MSO',
 ' JAX',
 ' MRY',
 ' MOD',
 ' LAM',
 'PAGA',
 'PAKT',
 'PAVD',
 'PAIL',
 'PACD',
 'PASN']

In [10]:
len(flight)#53103315

91134360

In [12]:
#flight = flight[(flight['DEP_LOCID'].isin(Airports_temp))&(flight['ARR_LOCID'].isin(Airports_temp))]

In [13]:
#len(flight)#91134360
#Number of flights OD pairs all within U.S.

91134360

In [11]:
airport = airport[airport['LOCID'].isin(Airports)]
len(airport)#all flights in airport 490

490

In [15]:
#flight.to_csv('flight.csv')

In [12]:
center = pd.read_csv('../../GDP/AirportLoc/US_center_apt.CSV').drop('Unnamed: 0',axis=1)
centers = []
for i in range(len(center)):
    for j in range(len(eval(center.iloc[i]['AIRPORT']))):
        centers.append([center.iloc[i]['Con_Zone'],' '+eval(center.iloc[i]['AIRPORT'])[j]])
centers = pd.DataFrame(centers,columns = ['Zone','Airport'])#ZAN, ZHN
#get ARTCC center excluding ZAN and ZHN

In [13]:
wrong = [' AZA',
 ' BKG',
 #' DFW',#RRO TX
 ' CLD',
 ' FCA',
 ' FWH',
 ' HAR',
 ' HHH',
 #' DFW',#HRL TX
 #' DFW',#LRD TX
 #' DFW',#MFE TX
 ' QQT',
 #' PHL',#UNV PA
 ' SGJ',
 ' XXW']
correct = [' IWA',
 ' BBG',
 #' BRO',
 ' CRQ',
 ' GPI',
 ' NFW',
 ' CXY',
 ' HXD',
 #' HRL',
 #' LRD',
 #' MFE',
 ' FFC',
 #' UNV',
 ' SGJ',
 ' LCQ']
centers = centers.replace(wrong,correct)

In [14]:
centers_append = pd.DataFrame(columns = ['Zone','Airport'])
centers_append['Zone'] = ['ZFW','ZFW','ZFW','ZFW','ZDC','ZFW','ZOA']
centers_append['Airport'] = [' RRO',' HRL',' LRD',' MFE',' UNV',' BRO',' SGJ']
centers = pd.concat([centers,centers_append])
#Adjust data

In [15]:
airport = airport.merge(centers,left_on = 'LOCID',right_on = 'Airport',how = 'left')
len(airport[airport['AIRPORT_STATE_CODE'].isin(['HI','AK'])])

36

In [16]:
airport['Zone'] = airport.apply(lambda row: 'ZHN' if row.AIRPORT_STATE_CODE=='HI' else 'ZAN' if row.AIRPORT_STATE_CODE=='AK' else row.Zone,axis=1)

In [17]:
airport = airport[['AIRPORT_STATE_CODE', 'LATITUDE', 'LONGITUDE', 'AIRPORT', 'LOCID',
       'Zone']]

In [18]:
airport.loc[490] = ['AK',0,0,'PAGA','PAGA','ZAN']
airport.loc[491] = ['AK',0,0,'PAKT','PAKT','ZAN']
airport.loc[492] = ['AK',0,0,'PAVD','PAVD','ZAN']
airport.loc[493] = ['AK',0,0,'PAIL','PAIL','ZAN']
airport.loc[494] = ['AK',0,0,'PACD','PACD','ZAN']
airport.loc[495] = ['AK',0,0,'PASN','PASN','ZAN']

In [19]:
airport

    AIRPORT_STATE_CODE   LATITUDE   LONGITUDE AIRPORT LOCID Zone
0                   PA  40.652222  -75.440556     ABE   ABE  ZNY
1                   TX  32.411389  -99.681944     ABI   ABI  ZFW
2                   NM  35.038889 -106.608333     ABQ   ABQ  ZAB
3                   SD  45.446667  -98.422500     ABR   ABR  ZMP
4                   GA  31.535556  -84.194444     ABY   ABY  ZJX
..                 ...        ...         ...     ...   ...  ...
491                 AK   0.000000    0.000000    PAKT  PAKT  ZAN
492                 AK   0.000000    0.000000    PAVD  PAVD  ZAN
493                 AK   0.000000    0.000000    PAIL  PAIL  ZAN
494                 AK   0.000000    0.000000    PACD  PACD  ZAN
495                 AK   0.000000    0.000000    PASN  PASN  ZAN

[496 rows x 6 columns]

In [24]:
#all airports in ASPM dataset with their location and Zone

In [20]:
centerAirports = centers[centers['Airport'].isin(L)]
countZone = centerAirports.groupby('Zone').count().reset_index()
singleZones = list(countZone[countZone['Airport']==1]['Zone'])
singleZones.append('ZHN')
singleZones.append('ZAN')
multiZones = list(countZone[countZone['Airport']!=1]['Zone'])

In [21]:
import math

def haversine(lat1, lon1, lat2, lon2):
    # Radius of the Earth in kilometers
    R = 6371.0  
    
    # Convert latitude and longitude from degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)
    
    # Differences in coordinates
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    # Haversine formula
    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    # Distance in kilometers
    distance = R * c
    
    return distance

In [22]:
airport

    AIRPORT_STATE_CODE   LATITUDE   LONGITUDE AIRPORT LOCID Zone
0                   PA  40.652222  -75.440556     ABE   ABE  ZNY
1                   TX  32.411389  -99.681944     ABI   ABI  ZFW
2                   NM  35.038889 -106.608333     ABQ   ABQ  ZAB
3                   SD  45.446667  -98.422500     ABR   ABR  ZMP
4                   GA  31.535556  -84.194444     ABY   ABY  ZJX
..                 ...        ...         ...     ...   ...  ...
491                 AK   0.000000    0.000000    PAKT  PAKT  ZAN
492                 AK   0.000000    0.000000    PAVD  PAVD  ZAN
493                 AK   0.000000    0.000000    PAIL  PAIL  ZAN
494                 AK   0.000000    0.000000    PACD  PACD  ZAN
495                 AK   0.000000    0.000000    PASN  PASN  ZAN

[496 rows x 6 columns]

In [23]:
huborzone = []
for i in range(len(airport)):
    if airport.iloc[i]['Zone'] in singleZones:
        huborzone.append(airport.iloc[i]['Zone'])
    else:
        temp = airport[(airport['LOCID'].isin(L))&(airport['Zone']==airport.iloc[i]['Zone'])]
        lat = airport.iloc[i]['LATITUDE']
        long = airport.iloc[i]['LONGITUDE']
        temp['dis'] = temp.apply(lambda row: haversine(lat,long,row.LATITUDE,row.LONGITUDE), axis=1)
        huborzone.append(temp.iloc[np.argmin(temp['dis'])]['LOCID'])

In [24]:
airport['huborzone'] = huborzone

In [25]:
## Airport Grouping according to ARTCC/large hub
## ref. TC1_Jing.pptx,Page 10
airport.groupby(['Zone','huborzone']).count()

                AIRPORT_STATE_CODE  LATITUDE  LONGITUDE  AIRPORT  LOCID
Zone huborzone
ZAB  ZAB                        16        16         16       16     16
ZAN  ZAN                        33        33         33       33     33
ZAU   MDW                       13        13         13       13     13
      ORD                       11        11         11       11     11
ZBW  ZBW                        34        34         34       34     34
ZDC   BWI                        3         3          3        3      3
      DCA                        9         9          9        9      9
      IAD                        9         9          9        9      9
      PHL                        4         4          4        4      4
ZDV  ZDV                        26        26         26       26     26
ZFW  ZFW                        24        24         24       24     24
ZHN  ZHN                         9         9          9        9      9
ZHU   AUS                        6         6          6        6      6
      IAH                       14        14         14       14     14
ZID  ZID                        15        15         15       15     15
ZJX   MCO                       13        13         13       13     13
      TPA                        9         9          9        9      9
ZKC  ZKC                        24        24         24       24     24
ZLA   LAS                        3         3          3        3      3
      LAX                       16        16         16       16     16
      SAN                        5         5          5        5      5
ZLC  ZLC                        25        25         25       25     25
ZMA   FLL                        7         7          7        7      7
      MIA                        4         4          4        4      4
ZME  ZME                        23        23         23       23     23
ZMP  ZMP                        44        44         44       44     44
ZNY   EWR                       11        11         11       11     11
      JFK                        1         1          1        1      1
      LGA                        2         2          2        2      2
ZOA  ZOA                        18        18         18       18     18
ZOB  ZOB                        24        24         24       24     24
ZSE  ZSE                        23        23         23       23     23
ZTL   ATL                       11        11         11       11     11
      CLT                        7         7          7        7      7

In [26]:
airportLocation = airport.copy()

In [27]:
airport = airport[['LOCID','huborzone']]
airport.columns = ['DEP_LOCID','huborzone']
airport

    DEP_LOCID huborzone
0         ABE       EWR
1         ABI       ZFW
2         ABQ       ZAB
3         ABR       ZMP
4         ABY       TPA
..        ...       ...
491      PAKT       ZAN
492      PAVD       ZAN
493      PAIL       ZAN
494      PACD       ZAN
495      PASN       ZAN

[496 rows x 2 columns]

In [28]:
airport.to_csv('airportHuborZone.csv')

In [30]:
len(flight)

91134360

In [31]:
flight = flight.merge(airport,on = 'DEP_LOCID')

In [32]:
huborzone_temp = airport['huborzone'].unique()

In [33]:
huborzone_temp

array([' EWR', 'ZFW', 'ZAB', 'ZMP', ' TPA', 'ZBW', 'ZSE', ' PHL', 'ZAN',
       ' DCA', ' IAH', ' CLT', ' ATL', 'ZDV', ' ORD', 'ZOB', ' MIA',
       ' AUS', ' MDW', ' LAX', ' LAS', 'ZOA', 'ZLC', 'ZME', 'ZID', 'ZKC',
       ' MCO', ' BWI', ' IAD', ' SAN', ' FLL', 'ZHN', ' JFK', ' LGA'],
      dtype=object)

In [34]:
count = flight.groupby(['DEP_YYYYMM','DEP_DAY','huborzone']).agg({'DEP_QTR':'count','arr_delay':'mean','dep_delay':'mean','DELAY_AIR':'mean'}).reset_index()

In [38]:
##Get 4*34 features daily with COVID and some empty

In [35]:
count#106585

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,201001,1,ATL,932,351.221030,414.512876,1.438841
1,201001,1,AUS,194,510.649485,604.948454,2.144330
2,201001,1,BWI,235,383.697872,430.944681,1.825532
3,201001,1,CLT,359,582.604457,522.701950,2.777159
4,201001,1,DCA,278,348.985612,324.068345,3.208633
...,...,...,...,...,...,...,...
181055,202407,31,ZME,471,982.978769,942.123142,3.530786
181056,202407,31,ZMP,609,2362.509031,2070.443350,4.003284
181057,202407,31,ZOA,938,706.745203,659.488273,3.072495
181058,202407,31,ZOB,700,1072.044286,1051.457143,3.490000
181059,202407,31,ZSE,849,858.078916,774.204947,3.514723

In [36]:
count1 = flight.groupby(['DEP_YYYYMM','DEP_DAY']).mean().reset_index()
count1 = count1[['DEP_YYYYMM','DEP_DAY']]
count1

      DEP_YYYYMM  DEP_DAY
0         201001        1
1         201001        2
2         201001        3
3         201001        4
4         201001        5
...          ...      ...
5321      202407       27
5322      202407       28
5323      202407       29
5324      202407       30
5325      202407       31

[5326 rows x 2 columns]

In [37]:
## Add weekday

In [38]:
count1['weekday'] = range(len(count1))
count1['weekday'] = count1.apply(lambda row: (row.weekday+5)%7+1,axis=1)

In [39]:
count = count[(count['DEP_YYYYMM']>=202106)|(count['DEP_YYYYMM']<202003)]
#count = count[count['DEP_YYYYMM']>201600]

In [40]:
count

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,201001,1,ATL,932,351.221030,414.512876,1.438841
1,201001,1,AUS,194,510.649485,604.948454,2.144330
2,201001,1,BWI,235,383.697872,430.944681,1.825532
3,201001,1,CLT,359,582.604457,522.701950,2.777159
4,201001,1,DCA,278,348.985612,324.068345,3.208633
...,...,...,...,...,...,...,...
181055,202407,31,ZME,471,982.978769,942.123142,3.530786
181056,202407,31,ZMP,609,2362.509031,2070.443350,4.003284
181057,202407,31,ZOA,938,706.745203,659.488273,3.072495
181058,202407,31,ZOB,700,1072.044286,1051.457143,3.490000
181059,202407,31,ZSE,849,858.078916,774.204947,3.514723

In [41]:
empty = []
for i in np.unique(count[['DEP_YYYYMM','DEP_DAY']], axis=0):
    for j in range(len(huborzone_temp)):
        empty.append([i[0],i[1],huborzone_temp[j]])
empty = pd.DataFrame(empty,columns = ['DEP_YYYYMM','DEP_DAY','huborzone'])
len(empty)#34*4869

165546

In [42]:
full = empty.merge(count,on = ['DEP_YYYYMM','DEP_DAY','huborzone'],how = 'left')
full = full.fillna(0)
full

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,201001,1,EWR,348.0,663.936782,774.925287,2.301724
1,201001,1,ZFW,986.0,672.471602,678.249493,1.201826
2,201001,1,ZAB,580.0,425.775862,524.198276,2.112069
3,201001,1,ZMP,443.0,692.316027,828.537246,2.932280
4,201001,1,TPA,274.0,644.773723,729.854015,3.014599
...,...,...,...,...,...,...,...
165541,202407,31,SAN,292.0,745.479452,684.452055,2.794521
165542,202407,31,FLL,330.0,978.851515,908.545455,3.627273
165543,202407,31,ZHN,382.0,506.777487,548.167539,0.939791
165544,202407,31,JFK,282.0,1237.028369,1069.574468,4.918440
165545,202407,31,LGA,362.0,2148.751381,1828.508287,3.353591

In [43]:
count1 = count1[(count1['DEP_YYYYMM']>=202106)|(count1['DEP_YYYYMM']<202003)]

In [44]:
## Get final 2678 day rows and 2+4*34 feature columns DataFrame

In [45]:
final = []
for i in range(len(count1)):
    temp = []
    temp.append(count1.iloc[i]['DEP_YYYYMM'])
    temp.append(count1.iloc[i]['DEP_DAY'])
    temp.append(count1.iloc[i]['weekday'])
    for j in range(34):
        temp.append(full.iloc[i*34+j]['DEP_QTR'])
        temp.append(full.iloc[i*34+j]['arr_delay'])
        temp.append(full.iloc[i*34+j]['dep_delay'])
        temp.append(full.iloc[i*34+j]['DELAY_AIR'])
    final.append(temp)

In [46]:
final = pd.DataFrame(final)
final

,0,1,2,3,4,5,6,7,8,9,...,129,130,131,132,133,134,135,136,137,138
0,201001,1,6,348.0,663.936782,774.925287,2.301724,986.0,672.471602,678.249493,...,564.080268,0.561873,273.0,1160.175824,1267.186813,2.113553,234.0,435.846154,522.764957,2.316239
1,201001,2,7,363.0,1995.545455,2232.203857,2.606061,953.0,979.572928,1044.833158,...,268.903654,0.720930,267.0,2429.558052,2596.790262,2.104869,226.0,738.557522,1024.650442,2.247788
2,201001,3,1,365.0,3172.460274,3715.221918,2.128767,1091.0,1122.727773,1120.966086,...,522.614841,1.515901,271.0,4058.136531,3908.634686,1.904059,304.0,2019.720395,2531.230263,1.950658
3,201001,4,2,432.0,1302.935185,1968.143519,2.020833,1123.0,964.936776,930.728406,...,633.333333,1.376344,266.0,864.364662,1342.327068,1.289474,352.0,415.593750,585.286932,2.125000
4,201001,5,3,402.0,697.124378,1233.266169,2.470149,1119.0,631.983021,642.403038,...,450.537879,0.848485,240.0,293.137500,646.658333,1.570833,364.0,204.994505,330.052198,2.425824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4864,202407,27,7,377.0,806.307692,905.729443,2.657825,1268.0,968.760252,1034.290221,...,564.461538,1.115385,271.0,405.321033,476.457565,2.601476,258.0,505.116279,598.604651,2.627907
4865,202407,28,1,390.0,1650.658974,1977.384615,2.830769,1344.0,1365.915179,1398.392857,...,335.510204,0.974490,286.0,642.972028,645.944056,3.524476,345.0,588.144928,718.434783,3.501449
4866,202407,29,2,406.0,1433.963054,1612.167488,2.352217,1343.0,1009.560685,1038.540581,...,402.096447,0.931472,286.0,1068.244755,1063.006993,3.493007,383.0,722.250653,911.906005,3.812010
4867,202407,30,3,375.0,1881.165333,1687.680000,3.352000,1314.0,1233.632420,1233.059361,...,377.076923,1.089744,283.0,1863.123675,1738.727915,3.840989,373.0,1881.654155,1190.991957,4.179625
4868,202407,31,4,393.0,2528.824427,1747.633588,3.445293,1309.0,1332.766234,1385.867074,...,548.167539,0.939791,282.0,1237.028369,1069.574468,4.918440,362.0,2148.751381,1828.508287,3.353591

In [47]:
final.to_csv('final_DEP.csv')