In [2]:
import pandas as pd
import numpy as np

In [3]:
#df = pd.read_csv('Cancelled.csv').drop('Unnamed: 0',axis=1)

In [4]:
flight = pd.read_csv('/Users/jing/Documents/Flight Data/DATA/ASPM2024-2025.8.CSV.gz')

In [5]:
a = ['PABE',' GPI','PAGA',' DGG',' SGJ',' HEF',' PFN']
b = [' BET',' FCA',' GAL',' RDB',' UST',' MNZ',' ECP']
flight = flight.replace(a,b)

In [6]:
flight = flight[flight['OAG']=='Y']

In [7]:
flight = flight[flight['USER_CLASS']=='C']

In [8]:
flight = flight[flight['FLT_TYPE']=='N']

In [9]:
flight = flight[(flight['DEP_LOCID'].isin(Airports_temp))&(flight['ARR_LOCID'].isin(Airports_temp))]

In [10]:
airport = pd.read_csv('airportHuborZone.csv').drop('Unnamed: 0',axis=1)

In [11]:
#DEP side

In [12]:
flight = flight.merge(airport,on = 'DEP_LOCID')

In [13]:
flight['dep_delay'] = flight.apply(lambda row: max(0, row.OOOI_DEP-row.OAG_S_DEP),axis=1)
flight['arr_delay'] = flight.apply(lambda row: max(0, row.OOOI_ARR-row.OAG_S_ARR),axis=1)

In [14]:
flight

,DEP_YYYYMM,DEP_DAY,DEP_HOUR,DEP_QTR,ARR_YYYYMM,ARR_DAY,ARR_HOUR,ARR_QTR,OFF_YYYYMM,OFF_DAY,...,T_ADJ_OAG_ARR,OOOI_ARR,T_OOOI_ARR,DELAY_TI,DIF_G2G,O_ARR_DEL,DELAY_ARR,huborzone,dep_delay,arr_delay
0,202408,30,19,3,202408,30,20,3,202408,31,...,14:01,1409596980,14:43,16.6,6,0,42,CLT,64380,64740
1,202505,8,18,1,202505,8,19,1,202505,9,...,12:05,1431276120,12:42,9.9,0,0,37,CLT,63480,63180
2,202508,8,17,4,202508,8,18,4,202508,8,...,18:50,1439161260,19:01,14.6,1,11,11,CLT,600,660
3,202508,10,20,3,202508,10,21,4,202508,10,...,22:03,1439345640,22:14,15.6,0,29,11,CLT,1860,1740
4,202508,11,17,4,202508,11,18,4,202508,11,...,19:24,1439423760,19:56,9.6,9,66,32,CLT,3420,3960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11360959,202506,2,12,2,202506,2,12,4,202506,2,...,12:45,1433360901,12:48,1.1,4,3,3,ZAB,0,201
11360960,202508,11,12,1,202508,11,12,2,202508,11,...,12:24,1439407577,12:26,2.1,0,2,2,ZAB,480,137
11360961,202503,27,15,2,202503,27,15,3,202503,27,...,21:21,1427602128,21:08,1.1,0,333,0,ZAB,20220,19968
11360962,202504,3,15,2,202504,3,15,3,202504,3,...,15:36,1428186171,15:22,3.1,6,0,0,ZAB,0,0
11360963,202508,7,15,2,202508,7,15,3,202508,7,...,15:36,1439071870,15:11,1.1,0,0,0,ZAB,0,0

In [15]:
count = flight.groupby(['DEP_YYYYMM','DEP_DAY','huborzone']).agg({'DEP_QTR':'count','arr_delay':'mean','dep_delay':'mean','DELAY_AIR':'mean'}).reset_index()

In [16]:
count

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,202401,1,ATL,730,328.906849,403.479452,2.121918
1,202401,1,AUS,362,453.812155,476.850829,1.613260
2,202401,1,BWI,268,457.164179,884.776119,0.977612
3,202401,1,CLT,517,526.435203,626.692456,1.854932
4,202401,1,DCA,322,297.577640,471.614907,1.745342
...,...,...,...,...,...,...,...
20701,202508,31,ZME,434,705.622120,715.023041,2.843318
20702,202508,31,ZMP,559,447.155635,447.799642,2.763864
20703,202508,31,ZOA,819,493.772894,540.000000,2.516484
20704,202508,31,ZOB,664,457.138554,507.289157,2.802711
20705,202508,31,ZSE,808,497.970297,480.965347,2.500000

In [17]:
count1 = flight.groupby(['DEP_YYYYMM','DEP_DAY']).mean().reset_index()
count1 = count1[['DEP_YYYYMM','DEP_DAY']]
count1

/var/folders/pd/42djns7x589bw787p86syckm0000gn/T/ipykernel_67678/2791151252.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  count1 = flight.groupby(['DEP_YYYYMM','DEP_DAY']).mean().reset_index()

     DEP_YYYYMM  DEP_DAY
0        202401        1
1        202401        2
2        202401        3
3        202401        4
4        202401        5
..          ...      ...
604      202508       27
605      202508       28
606      202508       29
607      202508       30
608      202508       31

[609 rows x 2 columns]

In [18]:
huborzone_temp = [' EWR', 'ZFW', 'ZAB', 'ZMP', ' TPA', 'ZBW', 'ZSE', ' PHL', 'ZAN',
       ' DCA', ' IAH', ' CLT', ' ATL', 'ZDV', ' ORD', 'ZOB', ' MIA',
       ' AUS', ' MDW', ' LAX', ' LAS', 'ZOA', 'ZLC', 'ZME', 'ZID', 'ZKC',
       ' MCO', ' BWI', ' IAD', ' SAN', ' FLL', 'ZHN', ' JFK', ' LGA']

In [19]:
empty = []
for i in np.unique(count[['DEP_YYYYMM','DEP_DAY']], axis=0):
    for j in range(len(huborzone_temp)):
        empty.append([i[0],i[1],huborzone_temp[j]])
empty = pd.DataFrame(empty,columns = ['DEP_YYYYMM','DEP_DAY','huborzone'])
len(empty)#34*4869

20706

In [20]:
full = empty.merge(count,on = ['DEP_YYYYMM','DEP_DAY','huborzone'],how = 'left')
full = full.fillna(0)
full

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,202401,1,EWR,353,279.464589,416.600567,1.580737
1,202401,1,ZFW,1107,428.776874,481.788618,2.142728
2,202401,1,ZAB,753,378.772908,414.342629,2.488712
3,202401,1,ZMP,464,280.991379,387.672414,2.398707
4,202401,1,TPA,295,795.108475,799.525424,1.654237
...,...,...,...,...,...,...,...
20701,202508,31,SAN,271,744.354244,849.741697,1.461255
20702,202508,31,FLL,325,1858.153846,1771.015385,1.670769
20703,202508,31,ZHN,321,144.859813,176.448598,0.591900
20704,202508,31,JFK,278,427.338129,607.769784,2.992806
20705,202508,31,LGA,343,572.011662,618.367347,3.647230

In [21]:
final = []
for i in range(len(count1)):
    temp = []
    temp.append(count1.iloc[i]['DEP_YYYYMM'])
    temp.append(count1.iloc[i]['DEP_DAY'])
    for j in range(34):
        temp.append(full.iloc[i*34+j]['DEP_QTR'])
        temp.append(full.iloc[i*34+j]['arr_delay'])
        temp.append(full.iloc[i*34+j]['dep_delay'])
        temp.append(full.iloc[i*34+j]['DELAY_AIR'])
    final.append(temp)

In [22]:
final = pd.DataFrame(final)
final

,0,1,2,3,4,5,6,7,8,9,...,128,129,130,131,132,133,134,135,136,137
0,202401,1,353,279.464589,416.600567,1.580737,1107,428.776874,481.788618,2.142728,...,380.962025,0.415190,246,390.000000,577.073171,1.906504,235,337.276596,545.361702,1.995745
1,202401,2,393,495.147583,648.091603,1.229008,1189,773.126997,776.972246,2.226241,...,854.062500,2.489583,259,557.837838,847.644788,1.602317,272,421.544118,663.308824,1.827206
2,202401,3,388,560.110825,638.350515,1.559278,1170,705.296581,727.538462,2.760684,...,614.931818,1.040404,248,553.790323,710.080645,2.459677,260,396.000000,537.461538,2.419231
3,202401,4,381,237.832021,344.251969,1.816273,1074,793.837989,772.793296,3.904097,...,502.748092,1.058524,225,374.133333,590.666667,1.968889,260,349.153846,546.692308,2.169231
4,202401,5,377,396.663130,497.188329,2.228117,1081,585.530065,594.782609,3.191489,...,355.223881,1.057214,221,619.276018,819.095023,3.638009,262,433.740458,583.282443,3.179389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,202508,27,398,397.545226,472.613065,2.158291,1132,501.678445,514.664311,1.602473,...,146.782609,0.571014,269,343.319703,267.434944,2.754647,405,368.148148,373.481481,2.911111
605,202508,28,426,2039.025822,2241.126761,2.579812,1109,2670.973850,2455.022543,2.331830,...,187.731092,0.613445,285,605.975439,705.684211,3.171930,399,449.646617,526.616541,4.781955
606,202508,29,427,732.976581,758.782201,2.637002,1219,1556.467596,1532.288761,1.776046,...,282.479339,0.746556,285,515.210526,605.263158,2.866667,404,494.579208,507.920792,3.341584
607,202508,30,370,465.567568,470.918919,2.586486,863,5493.674392,5154.785632,3.279258,...,517.413793,0.566092,270,764.918519,791.333333,3.788889,250,220.172000,271.920000,3.628000
608,202508,31,383,428.146214,486.422977,2.483029,1078,1851.539889,1728.423006,1.822820,...,176.448598,0.591900,278,427.338129,607.769784,2.992806,343,572.011662,618.367347,3.647230

In [23]:
final.to_csv('newDaysFinalDEP.csv')

In [24]:
final[final[0]==202406]

,0,1,2,3,4,5,6,7,8,9,...,128,129,130,131,132,133,134,135,136,137
152,202406,1,378,741.269841,819.206349,2.740741,1025,3815.473171,3472.039024,3.511220,...,514.353562,2.393140,268,782.910448,767.910448,4.272388,223,750.941704,575.784753,5.892377
153,202406,2,434,724.285714,777.373272,3.082949,1066,3864.799250,3674.015009,2.995310,...,367.485714,2.249351,287,585.829268,661.881533,3.296167,342,698.070175,709.473684,4.956140
154,202406,3,453,494.743929,564.370861,3.035320,1231,2713.108855,2299.642567,3.100731,...,293.939394,1.830808,288,374.065972,493.958333,4.350694,380,886.263158,936.000000,3.636842
155,202406,4,435,623.489655,585.517241,2.797701,1231,1386.706742,1258.196588,2.697807,...,326.684636,2.318059,277,693.357401,630.324910,3.891697,381,720.157480,515.590551,2.682415
156,202406,5,399,2019.035088,1958.796992,3.203008,1261,3323.980967,3248.183981,2.402062,...,492.837270,1.593176,259,1093.899614,1136.293436,4.289575,359,2012.089136,1747.186630,3.994429
157,202406,6,448,1426.330357,1419.776786,2.645089,1324,1307.907100,1342.114804,2.503776,...,543.121951,1.365854,283,1289.045936,1266.360424,2.660777,375,1566.560000,1053.120000,2.725333
158,202406,7,449,677.006682,644.899777,1.957684,1329,1170.579383,1232.460497,1.620015,...,1027.022333,1.332506,286,814.405594,605.244755,3.667832,379,441.530343,453.878628,1.854881
159,202406,8,386,495.564767,503.316062,2.393782,1246,971.227127,1107.640449,2.226324,...,579.844961,1.255814,270,404.666667,452.000000,2.266667,253,409.328063,472.648221,1.853755
160,202406,9,434,886.536866,913.686636,2.006912,1315,1367.404563,1425.307985,2.283650,...,297.371134,1.608247,288,699.791667,696.250000,2.354167,346,574.335260,522.832370,1.913295
161,202406,10,447,804.527964,935.704698,1.957494,1317,1648.925588,1646.104784,2.168565,...,221.232500,1.145000,287,330.313589,427.526132,1.996516,384,814.531250,837.343750,3.052083
162,202406,11,434,842.820276,905.115207,1.859447,1290,1804.936434,1714.372093,3.565116,...,307.978723,1.670213,284,880.563380,846.338028,4.510563,378,714.920635,751.428571,3.661376
163,202406,12,421,975.831354,1021.995249,2.662708,1280,1133.375781,1208.343750,2.378906,...,272.022556,1.385965,272,802.058824,790.808824,4.794118,361,755.401662,867.423823,3.132964
164,202406,13,438,981.372146,1038.219178,2.837900,1316,1116.425532,1134.209726,2.135258,...,462.537313,1.253731,272,960.444853,993.308824,4.238971,375,798.080000,927.360000,3.298667
165,202406,14,404,3661.247525,3284.851485,2.163366,1327,2019.945742,2016.081387,2.539563,...,342.951574,1.222760,265,2700.226415,2435.547170,3.920755,361,3144.099723,2845.595568,4.451524
166,202406,15,378,745.714286,904.603175,2.333333,1244,1073.623794,1101.414791,2.532154,...,485.356061,1.257576,268,1618.656716,1764.402985,2.720149,252,674.285714,888.809524,1.507937
167,202406,16,435,749.859770,762.896552,2.703448,1321,1195.354277,1234.100681,2.439818,...,483.358779,1.921120,287,960.418118,1085.017422,2.132404,347,780.000000,870.432277,2.919308
168,202406,17,446,730.762332,782.556054,2.486547,1336,926.462575,1000.688623,2.015719,...,539.851485,1.299505,287,1100.278746,1282.787456,2.620209,382,499.790576,552.879581,4.005236
169,202406,18,427,837.892272,686.557377,2.911007,1299,1010.800616,1082.725173,2.642032,...,286.870229,1.259542,284,490.774648,685.563380,2.725352,384,465.468750,505.625000,3.234375
170,202406,19,433,546.096998,710.577367,2.053118,1302,1139.556068,1187.741935,2.702765,...,316.279070,1.459948,285,438.947368,539.578947,3.105263,384,496.406250,627.968750,2.921875
171,202406,20,449,989.799555,999.821826,3.305122,1330,671.330075,700.285714,2.246617,...,315.984962,1.172932,287,808.850174,907.735192,3.912892,383,658.433420,538.746736,5.480418
172,202406,21,444,1607.702703,1150.810811,2.466216,1323,851.977324,863.990930,2.251701,...,399.952267,1.284010,286,1636.363636,1779.230769,2.447552,382,1170.628272,1306.335079,2.910995
173,202406,22,321,4605.794393,3591.028037,5.520249,1232,1068.034903,1062.857143,3.383117,...,369.804878,1.480488,259,3101.003861,2411.119691,3.965251,233,3952.017167,3149.098712,4.532189
174,202406,23,382,2789.026178,2744.136126,3.062827,1306,972.947933,1032.082695,2.079632,...,640.027094,1.514778,257,3425.136187,3298.832685,3.299611,310,3132.193548,2932.645161,5.138710
175,202406,24,446,1497.309417,1376.636771,3.174888,1333,1419.928732,1527.861965,2.152288,...,794.666667,1.725926,285,2510.315789,2121.894737,3.891228,378,1465.079365,1390.158730,3.492063
176,202406,25,432,1361.798611,1378.888889,3.069444,1288,1569.060559,1564.565217,3.673913,...,468.979592,1.170918,283,933.498233,960.636042,4.049470,381,1611.496063,1420.944882,6.971129
177,202406,26,393,3370.715013,2596.335878,4.346056,1288,2292.952640,2103.930901,4.421584,...,665.796345,1.114883,266,2026.015038,1507.218045,5.266917,340,3326.117647,2694.705882,3.388235
178,202406,27,424,2661.415094,2666.462264,3.193396,1319,1085.271418,1156.285064,2.463230,...,385.162228,1.317191,282,1980.851064,1885.319149,4.468085,360,2028.333333,1829.333333,4.702778
179,202406,28,448,921.046875,1032.991071,3.149554,1333,1180.462866,1283.180795,1.775694,...,471.952941,1.127059,286,1036.783217,966.923077,3.335664,382,624.659686,803.717277,3.591623
180,202406,29,386,1592.036269,1389.948187,5.580311,1244,1499.800643,1459.774920,4.673633,...,289.035354,1.424242,252,1951.428571,1834.761905,2.952381,258,1073.023256,1258.139535,4.790698
181,202406,30,320,4969.496875,4396.500000,3.778125,1297,1332.009252,1403.084040,2.343099,...,375.594059,1.101485,210,5202.857143,3782.857143,7.285714,256,4425.703125,3776.953125,8.476562

In [1]:
Airports_temp = [' LEB',
 ' IWA',
 ' PAH',
 ' SUN',
 ' ATY',
 ' MYR',
 ' PDT',
 ' DLG',
 ' VIS',
 ' ABY',
 ' PNS',
 ' AIA',
 ' SDP',
 ' BMI',
 ' BUF',
 ' MUO',
 ' PBG',
 ' ORH',
 ' DCA',
 ' CLT',
 ' HRO',
 ' GTR',
 ' CNM',
 ' STL',
 ' MQY',
 ' GRK',
 ' MHT',
 ' ORF',
 ' PIT',
 ' HVN',
 ' LNY',
 ' BFL',
 ' BET',
 ' ICT',
 ' TUS',
 ' BGM',
 ' BFD',
 ' FOD',
 ' GRI',
 ' CGI',
 ' IYK',
 ' EDW',
 ' BFM',
 ' MSN',
 ' BQK',
 ' BRL',
 ' CRP',
 ' ART',
 ' PKB',
 ' FOE',
 ' PHF',
 ' MSL',
 ' PRC',
 ' LIH',
 ' HSV',
 ' BPT',
 ' MCW',
 ' DLH',
 ' RAP',
 ' MSY',
 ' ELP',
 ' FKL',
 ' FSM',
 ' LWS',
 ' LAS',
 ' AKN',
 ' IND',
 ' JST',
 ' SGU',
 ' CVN',
 ' MSP',
 ' UNK',
 ' MEI',
 ' TUP',
 ' JNU',
 ' VEL',
 ' IAD',
 ' ALM',
 ' CDR',
 ' TUL',
 ' MHR',
 ' DUT',
 ' SIT',
 ' XNA',
 ' CID',
 ' MSS',
 ' UIN',
 ' FLO',
 ' TPA',
 ' CIC',
 ' WYS',
 ' ALS',
 ' GPM',
 ' MDW',
 ' BLI',
 ' TBN',
 ' ENA',
 ' DIK',
 ' HXD',
 ' TOL',
 ' CLE',
 ' BBG',
 ' AGS',
 ' IAH',
 ' EWB',
 ' ROC',
 ' FWA',
 ' LIT',
 ' LUK',
 ' ELD',
 ' MIA',
 ' YIP',
 ' CHS',
 ' GYY',
 ' DFW',
 ' ALW',
 ' SBA',
 ' COU',
 ' RDD',
 ' PIA',
 ' VPS',
 ' PIR',
 ' SAV',
 ' HOT',
 ' PBI',
 ' EVV',
 ' SWO',
 ' RNO',
 ' PIE',
 ' LAN',
 ' BHM',
 ' RIC',
 ' MCK',
 ' OKC',
 ' CRW',
 ' SYR',
 ' GTF',
 ' RFD',
 ' APF',
 ' MMU',
 ' BTL',
 ' MKG',
 ' MLI',
 ' LRD',
 ' ACK',
 ' DRT',
 ' RST',
 ' INL',
 ' GPT',
 ' ROA',
 ' IAG',
 ' GBD',
 ' HPN',
 ' CMH',
 ' BHB',
 ' HNL',
 ' MWA',
 ' ASE',
 ' BKW',
 ' WRG',
 ' PUW',
 ' IMT',
 ' OGD',
 ' AUG',
 ' RDM',
 ' SFB',
 ' BOI',
 ' HRL',
 ' DVL',
 ' FNT',
 ' TYS',
 ' ILG',
 ' TEX',
 ' MKC',
 ' SRQ',
 ' MLU',
 ' TYR',
 ' PGA',
 ' FLG',
 ' YNG',
 ' MFR',
 ' CWA',
 ' SBY',
 ' PGV',
 ' STC',
 ' JQF',
 ' BTM',
 ' ADK',
 ' RME',
 ' PVU',
 ' CEC',
 ' RSW',
 ' MKK',
 ' ABR',
 ' CSG',
 ' TVC',
 ' IPL',
 ' SPI',
 ' ATW',
 ' LBL',
 ' GGG',
 ' TWF',
 ' TTN',
 ' SBN',
 ' SHR',
 ' ATL',
 ' DAB',
 ' DRO',
 ' SEA',
 ' STS',
 ' GCC',
 ' VCV',
 ' HDN',
 ' RUT',
 ' CVG',
 ' JFK',
 ' BRW',
 ' OGG',
 ' PHX',
 ' MCI',
 ' LMT',
 ' PDX',
 ' HTS',
 ' RKS',
 ' BLV',
 ' ITO',
 ' PHL',
 ' EYW',
 ' SUX',
 ' PSP',
 ' LNK',
 ' LVK',
 ' JHM',
 ' ACV',
 ' RKD',
 ' CLL',
 ' FTW',
 ' DAL',
 ' GSO',
 ' CNY',
 ' AUO',
 ' SHD',
 ' PSG',
 ' LAX',
 ' FNL',
 ' ALB',
 ' KOA',
 ' MLB',
 ' IDA',
 ' OAK',
 ' MGW',
 ' CKB',
 ' MTJ',
 ' LSE',
 ' ROW',
 ' ONP',
 ' COS',
 ' FAY',
 ' EGE',
 ' PSM',
 ' FAT',
 ' PVD',
 ' YUM',
 ' DHN',
 ' MCO',
 ' ONT',
 ' BRO',
 ' ISP',
 ' TXK',
 ' HHR',
 ' ACY',
 ' GCK',
 ' BNA',
 ' BIL',
 ' PTK',
 ' MBS',
 ' PLN',
 ' LYH',
 ' SCK',
 ' MHK',
 ' ANI',
 ' GUS',
 ' CIU',
 ' TLH',
 ' LBF',
 ' ABE',
 ' SHV',
 ' BOS',
 ' RDU',
 ' MQT',
 ' MDT',
 ' SDF',
 ' CPR',
 ' OXR',
 ' CMX',
 ' SJC',
 ' ISN',
 ' ESC',
 ' JLN',
 ' BRD',
 ' DTW',
 ' CEZ',
 ' BTR',
 ' SOW',
 ' EWR',
 ' GJT',
 ' FFC',
 ' LGB',
 ' AEX',
 ' IPT',
 ' LUP',
 ' LBE',
 ' FAI',
 ' JAN',
 ' OAJ',
 ' LEX',
 ' AVP',
 ' GUC',
 ' HOM',
 ' PQI',
 ' OTH',
 ' BID',
 ' OMA',
 ' GLH',
 ' ADQ',
 ' HLN',
 ' DSM',
 ' SAN',
 ' ILM',
 ' GNV',
 ' ACT',
 ' CYS',
 ' PUB',
 ' UNV',
 ' LFT',
 ' GFK',
 ' ABQ',
 ' LGA',
 ' ABI',
 ' MCE',
 ' SWF',
 ' EAU',
 ' ITH',
 ' MMH',
 ' APN',
 ' EKO',
 ' TRI',
 ' BFI',
 ' PGD',
 ' SLC',
 ' OWB',
 ' PTH',
 ' TEB',
 ' LCH',
 ' BDL',
 ' FLL',
 ' SNA',
 ' ELM',
 ' RIW',
 ' MBL',
 ' GRB',
 ' BGR',
 ' VRB',
 ' PAM',
 ' ANC',
 ' JBR',
 ' CMI',
 ' BUR',
 ' GEG',
 ' HYA',
 ' DDC',
 ' DNV',
 ' FSD',
 ' HYS',
 ' OGS',
 ' NEW',
 ' GRR',
 ' COD',
 ' NFW',
 ' CXY',
 ' MAF',
 ' CDV',
 ' ADW',
 ' CHA',
 ' JAC',
 ' LCK',
 ' BED',
 ' CAK',
 ' MWH',
 ' IFP',
 ' HGR',
 ' CHO',
 ' SLE',
 ' SMX',
 ' ECP',
 ' LAR',
 ' BWG',
 ' VCT',
 ' RIV',
 ' SMF',
 ' MVY',
 ' SVC',
 ' CRQ',
 ' DEC',
 ' VNY',
 ' AZO',
 ' BWI',
 ' JHW',
 ' GSP',
 ' BMG',
 ' BZN',
 ' HON',
 ' DUJ',
 ' SGF',
 ' SBP',
 ' TVF',
 ' YAK',
 ' PDK',
 ' MOT',
 ' MCN',
 ' PAE',
 ' OME',
 ' SFO',
 ' LNS',
 ' YKM',
 ' LWB',
 ' MFE',
 ' KSM',
 ' IRK',
 ' BJI',
 ' KTN',
 ' BIS',
 ' PVC',
 ' DEN',
 ' PIH',
 ' DAY',
 ' SLN',
 ' SPS',
 ' JMS',
 ' SCC',
 ' ALO',
 ' VDZ',
 ' EAR',
 ' MGM',
 ' BFF',
 ' AUS',
 ' HOU',
 ' MKL',
 ' LCQ',
 ' EAT',
 ' AOO',
 ' AMA',
 ' OTZ',
 ' AVL',
 ' DBQ',
 ' ORD',
 ' OLV',
 ' MEM',
 ' SLK',
 ' IWD',
 ' HOB',
 ' HIB',
 ' RHI',
 ' SJT',
 ' VLD',
 ' EUG',
 ' UTM',
 ' SAT',
 ' SAF',
 ' LAF',
 ' CAE',
 ' PWM',
 ' ERI',
 ' MKE',
 ' AHN',
 ' CDC',
 ' BTV',
 ' MOB',
 ' PSC',
 ' EWN',
 ' FAR',
 ' BIH',
 ' LAW',
 ' PIB',
 ' LBB',
 ' MSO',
 ' JAX',
 ' MRY',
 ' MOD',
 ' LAM',
 'PAGA',
 'PAKT',
 'PAVD',
 'PAIL',
 'PACD',
 'PASN']