In [1]:
import pandas as pd
import numpy as np

In [3]:
flight = pd.read_csv('/Users/jing/Documents/Flight Data/DATA/ASPM2024-2025.8.CSV.gz')

In [4]:
a = ['PABE',' GPI','PAGA',' DGG',' SGJ',' HEF',' PFN']
b = [' BET',' FCA',' GAL',' RDB',' UST',' MNZ',' ECP']
flight = flight.replace(a,b)

In [5]:
flight = flight[flight['OAG']=='Y']

In [6]:
flight = flight[flight['USER_CLASS']=='C']

In [7]:
flight = flight[flight['FLT_TYPE']=='N']

In [8]:
flight = flight[(flight['DEP_LOCID'].isin(Airports_temp))&(flight['ARR_LOCID'].isin(Airports_temp))]

In [9]:
airport = pd.read_csv('airportHuborZone.csv').drop('Unnamed: 0',axis=1)

In [10]:
#DEP side

In [11]:
airport.columns = ['ARR_LOCID','huborzone']

In [12]:
flight = flight.merge(airport,on = 'ARR_LOCID')

In [13]:
flight['dep_delay'] = flight.apply(lambda row: max(0, row.OOOI_DEP-row.OAG_S_DEP),axis=1)
flight['arr_delay'] = flight.apply(lambda row: max(0, row.OOOI_ARR-row.OAG_S_ARR),axis=1)

In [14]:
flight

,DEP_YYYYMM,DEP_DAY,DEP_HOUR,DEP_QTR,ARR_YYYYMM,ARR_DAY,ARR_HOUR,ARR_QTR,OFF_YYYYMM,OFF_DAY,...,T_ADJ_OAG_ARR,OOOI_ARR,T_OOOI_ARR,DELAY_TI,DIF_G2G,O_ARR_DEL,DELAY_ARR,huborzone,dep_delay,arr_delay
0,202408,30,19,3,202408,30,20,3,202408,31,...,14:01,1409596980,14:43,16.6,6,0,42,CLT,64380,64740
1,202505,8,19,2,202505,8,21,4,202505,9,...,14:36,1431281220,14:07,6.9,28,972,0,CLT,56640,58320
2,202502,27,18,3,202502,27,21,4,202502,27,...,21:54,1425145200,12:40,5.4,0,0,0,CLT,0,0
3,202505,6,18,3,202505,6,21,4,202505,7,...,12:21,1431100920,12:02,2.9,0,848,0,CLT,51900,50880
4,202408,30,10,2,202408,30,12,4,202408,30,...,12:55,1409495100,10:25,0.6,0,0,0,CLT,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11360959,202503,31,12,4,202503,31,14,2,202503,31,...,16:21,1427938200,18:30,0.0,14,243,129,ZOA,13740,14580
11360960,202504,7,12,4,202504,7,14,2,202504,7,...,14:27,1428528253,14:24,0.0,6,0,0,ZOA,0,0
11360961,202505,5,12,4,202505,5,14,2,202505,5,...,14:27,1430947392,14:23,0.0,0,0,0,ZOA,240,0
11360962,202506,9,12,4,202506,9,14,2,202506,9,...,14:27,1433969400,13:50,0.0,0,0,0,ZOA,0,0
11360963,202508,6,16,1,202508,6,17,4,202508,6,...,17:54,1438994079,17:34,0.0,0,0,0,ZOA,0,0

In [15]:
count = flight.groupby(['DEP_YYYYMM','DEP_DAY','huborzone']).agg({'DEP_QTR':'count','arr_delay':'mean','dep_delay':'mean','DELAY_AIR':'mean'}).reset_index()

In [16]:
count

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,202401,1,ATL,723,328.698479,402.904564,0.858921
1,202401,1,AUS,367,417.547684,468.228883,2.013624
2,202401,1,BWI,269,540.505576,471.524164,1.494424
3,202401,1,CLT,520,543.832692,595.153846,2.853846
4,202401,1,DCA,326,435.644172,419.815951,3.561350
...,...,...,...,...,...,...,...
20701,202508,31,ZME,427,746.276347,806.557377,1.803279
20702,202508,31,ZMP,580,530.896552,530.482759,3.981034
20703,202508,31,ZOA,824,455.461165,516.043689,2.203883
20704,202508,31,ZOB,664,486.686747,546.054217,1.474398
20705,202508,31,ZSE,804,525.597015,616.716418,2.608209

In [17]:
count1 = flight.groupby(['DEP_YYYYMM','DEP_DAY']).mean().reset_index()
count1 = count1[['DEP_YYYYMM','DEP_DAY']]
count1

/var/folders/pd/42djns7x589bw787p86syckm0000gn/T/ipykernel_67657/2791151252.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  count1 = flight.groupby(['DEP_YYYYMM','DEP_DAY']).mean().reset_index()

     DEP_YYYYMM  DEP_DAY
0        202401        1
1        202401        2
2        202401        3
3        202401        4
4        202401        5
..          ...      ...
604      202508       27
605      202508       28
606      202508       29
607      202508       30
608      202508       31

[609 rows x 2 columns]

In [18]:
huborzone_temp = [' EWR', 'ZFW', 'ZAB', 'ZMP', ' TPA', 'ZBW', 'ZSE', ' PHL', 'ZAN',
       ' DCA', ' IAH', ' CLT', ' ATL', 'ZDV', ' ORD', 'ZOB', ' MIA',
       ' AUS', ' MDW', ' LAX', ' LAS', 'ZOA', 'ZLC', 'ZME', 'ZID', 'ZKC',
       ' MCO', ' BWI', ' IAD', ' SAN', ' FLL', 'ZHN', ' JFK', ' LGA']

In [19]:
empty = []
for i in np.unique(count[['DEP_YYYYMM','DEP_DAY']], axis=0):
    for j in range(len(huborzone_temp)):
        empty.append([i[0],i[1],huborzone_temp[j]])
empty = pd.DataFrame(empty,columns = ['DEP_YYYYMM','DEP_DAY','huborzone'])
len(empty)#34*4869

20706

In [20]:
full = empty.merge(count,on = ['DEP_YYYYMM','DEP_DAY','huborzone'],how = 'left')
full = full.fillna(0)
full

,DEP_YYYYMM,DEP_DAY,huborzone,DEP_QTR,arr_delay,dep_delay,DELAY_AIR
0,202401,1,EWR,355,487.535211,451.774648,2.191549
1,202401,1,ZFW,1130,473.729204,531.982301,1.730088
2,202401,1,ZAB,752,406.324468,466.755319,2.466755
3,202401,1,ZMP,460,417.513043,473.217391,2.119565
4,202401,1,TPA,298,553.614094,676.510067,0.852349
...,...,...,...,...,...,...,...
20701,202508,31,SAN,274,689.781022,649.051095,2.675182
20702,202508,31,FLL,317,1026.624606,1094.952681,3.851735
20703,202508,31,ZHN,320,226.687500,231.187500,0.790625
20704,202508,31,JFK,278,735.323741,899.784173,1.406475
20705,202508,31,LGA,343,817.609329,782.798834,2.746356

In [21]:
final = []
for i in range(len(count1)):
    temp = []
    temp.append(count1.iloc[i]['DEP_YYYYMM'])
    temp.append(count1.iloc[i]['DEP_DAY'])
    for j in range(34):
        temp.append(full.iloc[i*34+j]['DEP_QTR'])
        temp.append(full.iloc[i*34+j]['arr_delay'])
        temp.append(full.iloc[i*34+j]['dep_delay'])
        temp.append(full.iloc[i*34+j]['DELAY_AIR'])
    final.append(temp)

In [22]:
final = pd.DataFrame(final)
final

,0,1,2,3,4,5,6,7,8,9,...,128,129,130,131,132,133,134,135,136,137
0,202401,1,355,487.535211,451.774648,2.191549,1130,473.729204,531.982301,1.730088,...,310.812183,1.233503,243,794.320988,765.925926,3.144033,233,423.090129,459.399142,2.034335
1,202401,2,393,767.328244,693.740458,1.727735,1188,661.372054,653.484848,1.609428,...,643.792208,0.888312,263,1031.178707,771.558935,3.866920,277,626.209386,555.162455,0.989170
2,202401,3,389,384.431877,457.634961,1.948586,1168,738.733733,764.948630,2.568493,...,773.703797,1.678481,246,1060.243902,1082.926829,4.768293,261,548.168582,668.045977,2.160920
3,202401,4,381,380.572178,417.165354,2.228346,1077,894.623027,876.545961,2.841226,...,412.994924,1.489848,226,623.097345,642.212389,2.915929,264,377.045455,491.363636,1.465909
4,202401,5,376,303.510638,387.287234,1.989362,1081,820.653099,765.899167,3.073080,...,242.074074,1.395062,223,643.318386,711.659193,3.627803,262,465.343511,602.519084,1.889313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,202508,27,402,380.358209,372.686567,5.231343,1138,440.936731,456.959578,1.747803,...,230.728863,0.618076,270,320.666667,490.666667,1.703704,404,305.198020,384.801980,0.962871
605,202508,28,421,3248.125891,3181.140143,4.843230,1040,2212.241346,1876.557692,4.278846,...,300.000000,0.571031,283,652.197880,722.120141,3.049470,403,474.109181,550.570720,1.208437
606,202508,29,427,781.915691,850.538642,3.025761,1205,1390.833195,1381.344398,2.328631,...,495.945205,0.808219,282,337.624113,451.914894,2.407801,401,531.673317,574.264339,0.895262
607,202508,30,373,787.868633,800.107239,3.662198,817,4806.408813,3862.105263,5.511628,...,581.432665,0.722063,271,557.808118,692.546125,1.214022,252,400.714286,514.285714,0.765873
608,202508,31,384,753.125000,819.375000,2.109375,1067,1659.531396,1456.307404,3.294283,...,231.187500,0.790625,278,735.323741,899.784173,1.406475,343,817.609329,782.798834,2.746356

In [25]:
final.to_csv('newDaysFinalARR.csv')

In [2]:
Airports_temp = [' LEB',
 ' IWA',
 ' PAH',
 ' SUN',
 ' ATY',
 ' MYR',
 ' PDT',
 ' DLG',
 ' VIS',
 ' ABY',
 ' PNS',
 ' AIA',
 ' SDP',
 ' BMI',
 ' BUF',
 ' MUO',
 ' PBG',
 ' ORH',
 ' DCA',
 ' CLT',
 ' HRO',
 ' GTR',
 ' CNM',
 ' STL',
 ' MQY',
 ' GRK',
 ' MHT',
 ' ORF',
 ' PIT',
 ' HVN',
 ' LNY',
 ' BFL',
 ' BET',
 ' ICT',
 ' TUS',
 ' BGM',
 ' BFD',
 ' FOD',
 ' GRI',
 ' CGI',
 ' IYK',
 ' EDW',
 ' BFM',
 ' MSN',
 ' BQK',
 ' BRL',
 ' CRP',
 ' ART',
 ' PKB',
 ' FOE',
 ' PHF',
 ' MSL',
 ' PRC',
 ' LIH',
 ' HSV',
 ' BPT',
 ' MCW',
 ' DLH',
 ' RAP',
 ' MSY',
 ' ELP',
 ' FKL',
 ' FSM',
 ' LWS',
 ' LAS',
 ' AKN',
 ' IND',
 ' JST',
 ' SGU',
 ' CVN',
 ' MSP',
 ' UNK',
 ' MEI',
 ' TUP',
 ' JNU',
 ' VEL',
 ' IAD',
 ' ALM',
 ' CDR',
 ' TUL',
 ' MHR',
 ' DUT',
 ' SIT',
 ' XNA',
 ' CID',
 ' MSS',
 ' UIN',
 ' FLO',
 ' TPA',
 ' CIC',
 ' WYS',
 ' ALS',
 ' GPM',
 ' MDW',
 ' BLI',
 ' TBN',
 ' ENA',
 ' DIK',
 ' HXD',
 ' TOL',
 ' CLE',
 ' BBG',
 ' AGS',
 ' IAH',
 ' EWB',
 ' ROC',
 ' FWA',
 ' LIT',
 ' LUK',
 ' ELD',
 ' MIA',
 ' YIP',
 ' CHS',
 ' GYY',
 ' DFW',
 ' ALW',
 ' SBA',
 ' COU',
 ' RDD',
 ' PIA',
 ' VPS',
 ' PIR',
 ' SAV',
 ' HOT',
 ' PBI',
 ' EVV',
 ' SWO',
 ' RNO',
 ' PIE',
 ' LAN',
 ' BHM',
 ' RIC',
 ' MCK',
 ' OKC',
 ' CRW',
 ' SYR',
 ' GTF',
 ' RFD',
 ' APF',
 ' MMU',
 ' BTL',
 ' MKG',
 ' MLI',
 ' LRD',
 ' ACK',
 ' DRT',
 ' RST',
 ' INL',
 ' GPT',
 ' ROA',
 ' IAG',
 ' GBD',
 ' HPN',
 ' CMH',
 ' BHB',
 ' HNL',
 ' MWA',
 ' ASE',
 ' BKW',
 ' WRG',
 ' PUW',
 ' IMT',
 ' OGD',
 ' AUG',
 ' RDM',
 ' SFB',
 ' BOI',
 ' HRL',
 ' DVL',
 ' FNT',
 ' TYS',
 ' ILG',
 ' TEX',
 ' MKC',
 ' SRQ',
 ' MLU',
 ' TYR',
 ' PGA',
 ' FLG',
 ' YNG',
 ' MFR',
 ' CWA',
 ' SBY',
 ' PGV',
 ' STC',
 ' JQF',
 ' BTM',
 ' ADK',
 ' RME',
 ' PVU',
 ' CEC',
 ' RSW',
 ' MKK',
 ' ABR',
 ' CSG',
 ' TVC',
 ' IPL',
 ' SPI',
 ' ATW',
 ' LBL',
 ' GGG',
 ' TWF',
 ' TTN',
 ' SBN',
 ' SHR',
 ' ATL',
 ' DAB',
 ' DRO',
 ' SEA',
 ' STS',
 ' GCC',
 ' VCV',
 ' HDN',
 ' RUT',
 ' CVG',
 ' JFK',
 ' BRW',
 ' OGG',
 ' PHX',
 ' MCI',
 ' LMT',
 ' PDX',
 ' HTS',
 ' RKS',
 ' BLV',
 ' ITO',
 ' PHL',
 ' EYW',
 ' SUX',
 ' PSP',
 ' LNK',
 ' LVK',
 ' JHM',
 ' ACV',
 ' RKD',
 ' CLL',
 ' FTW',
 ' DAL',
 ' GSO',
 ' CNY',
 ' AUO',
 ' SHD',
 ' PSG',
 ' LAX',
 ' FNL',
 ' ALB',
 ' KOA',
 ' MLB',
 ' IDA',
 ' OAK',
 ' MGW',
 ' CKB',
 ' MTJ',
 ' LSE',
 ' ROW',
 ' ONP',
 ' COS',
 ' FAY',
 ' EGE',
 ' PSM',
 ' FAT',
 ' PVD',
 ' YUM',
 ' DHN',
 ' MCO',
 ' ONT',
 ' BRO',
 ' ISP',
 ' TXK',
 ' HHR',
 ' ACY',
 ' GCK',
 ' BNA',
 ' BIL',
 ' PTK',
 ' MBS',
 ' PLN',
 ' LYH',
 ' SCK',
 ' MHK',
 ' ANI',
 ' GUS',
 ' CIU',
 ' TLH',
 ' LBF',
 ' ABE',
 ' SHV',
 ' BOS',
 ' RDU',
 ' MQT',
 ' MDT',
 ' SDF',
 ' CPR',
 ' OXR',
 ' CMX',
 ' SJC',
 ' ISN',
 ' ESC',
 ' JLN',
 ' BRD',
 ' DTW',
 ' CEZ',
 ' BTR',
 ' SOW',
 ' EWR',
 ' GJT',
 ' FFC',
 ' LGB',
 ' AEX',
 ' IPT',
 ' LUP',
 ' LBE',
 ' FAI',
 ' JAN',
 ' OAJ',
 ' LEX',
 ' AVP',
 ' GUC',
 ' HOM',
 ' PQI',
 ' OTH',
 ' BID',
 ' OMA',
 ' GLH',
 ' ADQ',
 ' HLN',
 ' DSM',
 ' SAN',
 ' ILM',
 ' GNV',
 ' ACT',
 ' CYS',
 ' PUB',
 ' UNV',
 ' LFT',
 ' GFK',
 ' ABQ',
 ' LGA',
 ' ABI',
 ' MCE',
 ' SWF',
 ' EAU',
 ' ITH',
 ' MMH',
 ' APN',
 ' EKO',
 ' TRI',
 ' BFI',
 ' PGD',
 ' SLC',
 ' OWB',
 ' PTH',
 ' TEB',
 ' LCH',
 ' BDL',
 ' FLL',
 ' SNA',
 ' ELM',
 ' RIW',
 ' MBL',
 ' GRB',
 ' BGR',
 ' VRB',
 ' PAM',
 ' ANC',
 ' JBR',
 ' CMI',
 ' BUR',
 ' GEG',
 ' HYA',
 ' DDC',
 ' DNV',
 ' FSD',
 ' HYS',
 ' OGS',
 ' NEW',
 ' GRR',
 ' COD',
 ' NFW',
 ' CXY',
 ' MAF',
 ' CDV',
 ' ADW',
 ' CHA',
 ' JAC',
 ' LCK',
 ' BED',
 ' CAK',
 ' MWH',
 ' IFP',
 ' HGR',
 ' CHO',
 ' SLE',
 ' SMX',
 ' ECP',
 ' LAR',
 ' BWG',
 ' VCT',
 ' RIV',
 ' SMF',
 ' MVY',
 ' SVC',
 ' CRQ',
 ' DEC',
 ' VNY',
 ' AZO',
 ' BWI',
 ' JHW',
 ' GSP',
 ' BMG',
 ' BZN',
 ' HON',
 ' DUJ',
 ' SGF',
 ' SBP',
 ' TVF',
 ' YAK',
 ' PDK',
 ' MOT',
 ' MCN',
 ' PAE',
 ' OME',
 ' SFO',
 ' LNS',
 ' YKM',
 ' LWB',
 ' MFE',
 ' KSM',
 ' IRK',
 ' BJI',
 ' KTN',
 ' BIS',
 ' PVC',
 ' DEN',
 ' PIH',
 ' DAY',
 ' SLN',
 ' SPS',
 ' JMS',
 ' SCC',
 ' ALO',
 ' VDZ',
 ' EAR',
 ' MGM',
 ' BFF',
 ' AUS',
 ' HOU',
 ' MKL',
 ' LCQ',
 ' EAT',
 ' AOO',
 ' AMA',
 ' OTZ',
 ' AVL',
 ' DBQ',
 ' ORD',
 ' OLV',
 ' MEM',
 ' SLK',
 ' IWD',
 ' HOB',
 ' HIB',
 ' RHI',
 ' SJT',
 ' VLD',
 ' EUG',
 ' UTM',
 ' SAT',
 ' SAF',
 ' LAF',
 ' CAE',
 ' PWM',
 ' ERI',
 ' MKE',
 ' AHN',
 ' CDC',
 ' BTV',
 ' MOB',
 ' PSC',
 ' EWN',
 ' FAR',
 ' BIH',
 ' LAW',
 ' PIB',
 ' LBB',
 ' MSO',
 ' JAX',
 ' MRY',
 ' MOD',
 ' LAM',
 'PAGA',
 'PAKT',
 'PAVD',
 'PAIL',
 'PACD',
 'PASN']